Improve workflows

diff --git a/.github/workflows/test-stable.yaml b/.github/workflows/test-stable.yaml
--- a/.github/workflows/test-stable.yaml
+++ b/.github/workflows/test-stable.yaml
@@ -28,6 +28,26 @@ jobs:
             macos-14,
             macos-15-intel,
           ]
+        python-version:
+          ["3.14", "3.14t", "3.13", "3.13t", "3.12", "3.11", "3.10"]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.5
+        with:
+          package-name: myproject
+          python-version: ${{ matrix.python-version }}
+
+  test-extra:
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    strategy:
+      max-parallel: 8
+      fail-fast: false
+      matrix:
         dist-type: ["sdist", "wheel"]
         package-extra: ["", "all"]
 
@@ -42,39 +62,6 @@ jobs:
           package-name: myproject
           package-extra: ${{ matrix.package-extra }}
           package-dependencies: coola
-
-  test-python:
-    runs-on: ${{ matrix.os }}
-    timeout-minutes: 2
-    strategy:
-      max-parallel: 8
-      fail-fast: false
-      matrix:
-        os:
-          [
-            ubuntu-latest,
-            ubuntu-24.04,
-            ubuntu-22.04,
-            ubuntu-24.04-arm,
-            ubuntu-22.04-arm,
-            macos-latest,
-            macos-26,
-            macos-15,
-            macos-14,
-            macos-15-intel,
-          ]
-        python-version:
-          ["3.14", "3.14t", "3.13", "3.13t", "3.12", "3.11", "3.10"]
-
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v6
-
-      - name: Verify Build
-        uses: durandtibo/verify-uv-build-action@v0.0.5
-        with:
-          package-name: myproject
-          python-version: ${{ matrix.python-version }}
 
   #################################
   #     Tests to check inputs     #
@@ -113,11 +100,6 @@ jobs:
     outputs:
       action_failed: ${{ steps.run_action.outcome == 'failure' }}
     timeout-minutes: 2
-    strategy:
-      max-parallel: 8
-      fail-fast: false
-      matrix:
-        dist-type: ["sdist", "wheel"]
 
     steps:
       - name: Checkout
@@ -132,7 +114,35 @@ jobs:
         uses: durandtibo/verify-uv-build-action@v0.0.5
         with:
           package-name: myproject
-          dist-type: ${{ matrix.dist-type }}
+        continue-on-error: true
+
+      - name: Failure - it did not fail as expected
+        if: steps.run_action.outcome != 'failure'
+        run: |
+          echo "❌ Error: Step should have failed but didn't!"
+          exit 1
+
+      - name: Success - it failed as expected
+        if: steps.run_action.outcome == 'failure'
+        run: echo "✅ Test passed - step failed as expected"
+
+  incorrect-extra:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    outputs:
+      action_failed: ${{ steps.run_action.outcome == 'failure' }}
+    timeout-minutes: 2
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Call composite action
+        id: run_action
+        uses: durandtibo/verify-uv-build-action@v0.0.5
+        with:
+          package-name: myproject
+          package-extra: missing
         continue-on-error: true
 
       - name: Failure - it did not fail as expected
