Update workflows (#37)

diff --git a/.github/workflows/test-stable.yaml b/.github/workflows/test-stable.yaml
--- a/.github/workflows/test-stable.yaml
+++ b/.github/workflows/test-stable.yaml
@@ -97,14 +97,50 @@ jobs:
           package-name: myproject
         continue-on-error: true
 
-      - name: Report failure detection
-        run: echo "Action failed? ${{ steps.run_action.outcome }}"
-
-  verify-failure-dist-type:
-    runs-on: ubuntu-latest
-    needs: invalid-dist-type
-    if: ${{ needs.invalid-dist-type.outputs.action_failed != 'true' }}
-    steps:
-      - run: |
-          echo "❌ Composite action did NOT fail with invalid input (but should)."
+      - name: Failure - it did not fail as expected
+        if: steps.run_action.outcome != 'failure'
+        run: |
+          echo "❌ Error: Step should have failed but didn't!"
           exit 1
+
+      - name: Success - it failed as expected
+        if: steps.run_action.outcome == 'failure'
+        run: echo "✅ Test passed - step failed as expected"
+
+  missing-py-typed:
+    runs-on: ubuntu-latest
+    continue-on-error: true
+    outputs:
+      action_failed: ${{ steps.run_action.outcome == 'failure' }}
+    timeout-minutes: 10
+    strategy:
+      max-parallel: 8
+      fail-fast: false
+      matrix:
+        dist-type: ["sdist", "wheel"]
+
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove py.typed
+        run: |
+          rm src/myproject/py.typed
+
+      - name: Call composite action
+        id: run_action
+        uses: durandtibo/verify-uv-build-action@v0.0.4
+        with:
+          package-name: myproject
+          dist-type: ${{ matrix.dist-type }}
+        continue-on-error: true
+
+      - name: Failure - it did not fail as expected
+        if: steps.run_action.outcome != 'failure'
+        run: |
+          echo "❌ Error: Step should have failed but didn't!"
+          exit 1
+
+      - name: Success - it failed as expected
+        if: steps.run_action.outcome == 'failure'
+        run: echo "✅ Test passed - step failed as expected"
