Add workflow to test published action (#13)

diff --git a/.github/workflows/test-stable.yaml b/.github/workflows/test-stable.yaml
--- a/.github/workflows/test-stable.yaml
+++ b/.github/workflows/test-stable.yaml
@@ -5,7 +5,6 @@ on:
   workflow_dispatch: # to trigger manually
 
 permissions:
-  actions: write
   contents: read
 
 jobs:
@@ -17,7 +16,134 @@ jobs:
       fail-fast: false
       matrix:
         os: [ubuntu-24.04]
+        dist-type: ["sdist", "wheel"]
+        package-extra: ["", "all"]
 
     steps:
       - name: Checkout
         uses: actions/checkout@v6
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: ${{ matrix.dist-type }}
+          package-name: myproject
+          package-extra: ${{ matrix.package-extra }}
+
+  invalid-dist-type:
+    runs-on: ubuntu-24.04
+    continue-on-error: true
+    outputs:
+      action_failed: ${{ steps.run_action.outcome == 'failure' }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Call composite action with invalid value
+        id: run_action
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: tar
+          package-name: myproject
+        continue-on-error: true
+
+      - name: Report failure detection
+        run: echo "Action failed? ${{ steps.run_action.outcome }}"
+
+  verify-failure-dist-type:
+    runs-on: ubuntu-24.04
+    needs: invalid-dist-type
+    if: ${{ needs.invalid-dist-type.outputs.action_failed != 'true' }}
+    steps:
+      - run: |
+          echo "❌ Composite action did NOT fail with invalid input (but should)."
+          exit 1
+
+  #############################################
+  #     Tests robustness to missing files     #
+  #############################################
+
+  missing-all:
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove scripts
+        run: |
+          rm dev/package/*
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: wheel
+          package-name: myproject
+
+  missing-check-metadata:
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove check metadata script
+        run: |
+          rm dev/package/check_metadata.sh
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: wheel
+          package-name: myproject
+
+  missing-check-dependency-tree:
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove check dependency tree script
+        run: |
+          rm dev/package/check_dependency_tree.sh
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: wheel
+          package-name: myproject
+
+  missing-check-type:
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove check type script
+        run: |
+          rm dev/package/check_type.sh
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: wheel
+          package-name: myproject
+
+  missing-custom-checks:
+    runs-on: ubuntu-24.04
+    timeout-minutes: 10
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+
+      - name: Remove custom checks script
+        run: |
+          rm dev/package/custom_checks.sh
+
+      - name: Verify Build
+        uses: durandtibo/verify-uv-build-action@v0.0.1
+        with:
+          dist-type: wheel
+          package-name: myproject
